### ISSUE TITLE
Softlock at Myahm Agana shrine upon entry

### ISSUE THREAD

**Issue by Sunny-Solaire** [CEObrainz/Second-Wind#11]
S̳o̳l̳a̳i̳r̳e̳#2011 or SunnyD

Platform: Cemu 1.26.2f

Mod Version: 1.9.11b

Game Version: 208 with all the DLC, Region USA

Detailed description of the issue: 
       The game will proceed through the entry cinematic of the Myahm Agana shrine as normal until you see pop-up for the shrine name and the text with that. After that your character will be stuck in the animation where they are looking around the shrine only moving their head. The only thing that the game will let you do afterwards, is simply focus your camera or try to lock on to something. No menus, movement, or anything else.
       Additionally, skipping through the entry cinematic will only lead to a black screen, as if the game has crashed.

Exact steps to reproduce the issue:
1. Go to Myahm Agana shrine in Hateno Village

2. Enter the shrine

3. Behold the error

**Comment by CEObrainz** [comment]
This issue is resolved by following the troubleshooting steps on the Discord

1) Turn off the Draw Distance Mod 
2) Set Shadows to Medium (this is the default)
3) If the above don't work, use the Extended Memory Pack

In addition, please make sure you aren't using any other mods that could be deemed as incompatible with Second Wind by checking through this page: https://secondwind.fandom.com/wiki/Mod_Compatibility
